export const sponsorshipBasePath = "/sponsorship-opportunities";
export const sponsorshipAssetPath = "/sponsorships";

export const sponsorshipDecks = [
  {
    slug: "all",
    title: "All Sponsorship Opportunities",
    shortTitle: "NEOChosen 2026 Sponsorship Overview",
    description: "Compare presenting, event, community, advertising, and activation opportunities available throughout the NEOChosen 2026 weekend.",
    price: "Opportunities from $250 to $12,500+",
    priceLabel: "Opportunity range",
    availability: "",
    category: "Sponsorship Overview",
    cta: "View All Opportunities",
    pdfFile: "01_NEOChosen_Master_Sponsorship_Overview.pdf",
    summaryImage: "01_NEOChosen_Master_Sponsorship_Overview.png",
    summaryWidth: 1800,
    summaryHeight: 1436,
    metaTitle: "NEOChosen 2026 Sponsorship Opportunities | NEOChosen",
    metaDescription: "Compare NEOChosen 2026 presenting, event, community, advertising, and activation sponsorship opportunities across Northeast Ohio.",
    featured: "overview"
  },
  {
    slug: "weekend",
    title: "Whole-Weekend Presenting Partnership",
    shortTitle: "Whole-Weekend Presenting Partnership",
    description: "Become one of NEOChosen's premier partners with top-level recognition, visibility, hospitality, and engagement throughout the entire November 13–15 weekend.",
    price: "$12,500",
    priceLabel: "Investment",
    availability: "Maximum of two presenting sponsors.",
    category: "Presenting Partnership",
    cta: "View Presenting Partnership",
    pdfFile: "02_Whole_Weekend_Presenting_Partnership.pdf",
    summaryImage: "02_Whole_Weekend_Presenting_Partnership.png",
    summaryWidth: 1800,
    summaryHeight: 1174,
    metaTitle: "Whole-Weekend Presenting Sponsor | NEOChosen 2026",
    metaDescription: "Explore the $12,500 NEOChosen 2026 Whole-Weekend Presenting Partnership, including recognition, hospitality, and engagement benefits."
  },
  {
    slug: "piano-guys",
    title: "The Piano Guys Concert Sponsorship",
    shortTitle: "The Piano Guys Concert Sponsorship",
    description: "Partner with the weekend's largest individual event at the Akron Civic Theatre and reach up to 2,500 paid guests.",
    price: "$500–$9,000",
    priceLabel: "Sponsorship range",
    availability: "",
    category: "Event Sponsorship",
    cta: "View Concert Sponsorships",
    pdfFile: "03_Piano_Guys_Concert_Sponsorship.pdf",
    summaryImage: "03_Piano_Guys_Concert_Sponsorship.png",
    summaryWidth: 1800,
    summaryHeight: 1248,
    metaTitle: "The Piano Guys Concert Sponsorship | NEOChosen 2026",
    metaDescription: "Review NEOChosen 2026 sponsorship opportunities for The Piano Guys concert at the Akron Civic Theatre."
  },
  {
    slug: "leadership-breakfasts",
    title: "Religious & Civic Leadership Breakfasts",
    shortTitle: "Leadership Breakfasts Sponsorship",
    description: "Connect with pastors, executives, nonprofit leaders, educators, civic officials, and other trusted Northeast Ohio decision-makers.",
    price: "$500–$6,000",
    priceLabel: "Sponsorship range",
    availability: "",
    category: "Leadership Sponsorship",
    cta: "View Breakfast Sponsorships",
    pdfFile: "04_Religious_Civic_Leadership_Breakfasts_Sponsorship.pdf",
    summaryImage: "04_Religious_Civic_Leadership_Breakfasts_Sponsorship.png",
    summaryWidth: 1800,
    summaryHeight: 1376,
    metaTitle: "Leadership Breakfast Sponsorship | NEOChosen 2026",
    metaDescription: "Explore sponsorship opportunities for NEOChosen's 2026 Religious and Civic Leadership Breakfasts in Northeast Ohio."
  },
  {
    slug: "lakewood",
    title: "NEOChosen Lakewood",
    shortTitle: "NEOChosen Lakewood Sponsorship",
    description: "Sponsor the Friday evening Lakewood experience featuring cast members from The Chosen with approximately 1,700 projected attendees.",
    price: "$500–$7,500",
    priceLabel: "Sponsorship range",
    availability: "",
    category: "Event Sponsorship",
    cta: "View Lakewood Sponsorships",
    pdfFile: "05_NEOChosen_Lakewood_Sponsorship.pdf",
    summaryImage: "05_NEOChosen_Lakewood_Sponsorship.png",
    summaryWidth: 1800,
    summaryHeight: 1192,
    metaTitle: "Lakewood Sponsorship Opportunities | NEOChosen 2026",
    metaDescription: "Review NEOChosen Lakewood sponsorship opportunities for the November 13, 2026 event featuring cast members from The Chosen."
  },
  {
    slug: "meet-and-greet",
    title: "Meet & Greet Experiences",
    shortTitle: "Meet & Greet Sponsorship",
    description: "Support personal community experiences at the Fairlawn and Chesterland locations and connect directly with attendees in a smaller, interactive setting.",
    price: "$500–$5,000",
    priceLabel: "Sponsorship range",
    availability: "",
    category: "Event Sponsorship",
    cta: "View Meet & Greet Sponsorships",
    pdfFile: "06_Meet_Greet_Sponsorship.pdf",
    summaryImage: "06_Meet_Greet_Sponsorship.png",
    summaryWidth: 1800,
    summaryHeight: 1292,
    metaTitle: "Meet & Greet Sponsorship Opportunities | NEOChosen 2026",
    metaDescription: "Explore sponsorship opportunities for NEOChosen Meet & Greet experiences in Fairlawn and Chesterland."
  },
  {
    slug: "vip-dinner",
    title: "VIP Donor Dinner",
    shortTitle: "VIP Donor Dinner Sponsorship",
    description: "Partner with an intimate gathering of approximately 300 sponsors, donors, business leaders, pastors, nonprofit executives, and community leaders.",
    price: "$200–$7,500",
    priceLabel: "Sponsorship range",
    availability: "",
    category: "Event Sponsorship",
    cta: "View Dinner Sponsorships",
    pdfFile: "07_VIP_Donor_Dinner_Sponsorship.pdf",
    summaryImage: "07_VIP_Donor_Dinner_Sponsorship.png",
    summaryWidth: 1800,
    summaryHeight: 1376,
    metaTitle: "VIP Donor Dinner Sponsorship | NEOChosen 2026",
    metaDescription: "Review NEOChosen 2026 VIP Donor Dinner sponsorship opportunities for an intimate gathering of regional leaders and supporters."
  },
  {
    slug: "community",
    title: "Community & Small Business Sponsorships",
    shortTitle: "Community Sponsorship",
    description: "Flexible partnership opportunities for businesses and organizations that want to support NEOChosen through sponsorships, booths, advertising, and community engagement.",
    price: "$250–$5,000+",
    priceLabel: "Sponsorship range",
    availability: "",
    category: "Community Sponsorship",
    cta: "View Community Opportunities",
    pdfFile: "08_Community_Sponsorship.pdf",
    summaryImage: "08_Community_Sponsorship.png",
    summaryWidth: 1800,
    summaryHeight: 1876,
    metaTitle: "Community Sponsorship Opportunities | NEOChosen 2026",
    metaDescription: "Explore approachable NEOChosen 2026 sponsorship, booth, advertising, and activation opportunities for local businesses and community partners.",
    featured: "community"
  }
];
